// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
package com.mapconductor.icons.us

import com.mapconductor.icons.MapIconGlyph

/** us pack map symbols. Selection is always explicit. */
object UnitedStatesMapIcons {
    /** United States post office. */
    val postOffice =
        MapIconGlyph(
            id = "us.post_office",
            pathData = "M12 2 L22 7 L2 7 Z M3 9 L21 9 L21 12 L3 12 Z M4 12 L7 12 L7 19 L4 19 Z M9 12 L12 12 L12 19 L9 19 Z M14 12 L17 12 L17 19 L14 19 Z M19 12 L21 12 L21 19 L19 19 Z M2 19 L22 19 L22 22 L2 22 Z",
        )

    /** United States police station. */
    val policeStation =
        MapIconGlyph(
            id = "us.police_station",
            pathData = "M12 2 L21 5 L20 14 C19 19 15 21 12 22 C9 21 5 19 4 14 L3 5 Z",
        )

    /** United States Interstate highway. */
    val interstate =
        MapIconGlyph(
            id = "us.interstate",
            pathData = "M3 5 C7 3 9 4 12 2 C15 4 17 3 21 5 L20 14 C19 19 15 21 12 22 C9 21 5 19 4 14 Z",
        )
}
